export const SEED_DATA: Record<string, { ru: Record<string,string>; uz: Record<string,string>; en: Record<string,string> }> = {
  "hero": {
    "ru": {
      "badge": "IT Park Resident · Ташкент, Узбекистан",
      "title": "Технологии, которые",
      "titleAccent": "меняют бизнес",
      "subtitle": "IVN Labs — команда разработчиков, создающих умные решения: от AI-агентов до корпоративных платформ. Мы трансформируем идеи в продукт.",
      "ctaPrimary": "Начать проект",
      "ctaSecondary": "Смотреть кейсы",
      "stat1Value": "5+",
      "stat1Label": "лет опыта",
      "stat2Value": "50+",
      "stat2Label": "проектов",
      "stat3Value": "20+",
      "stat3Label": "клиентов"
    },
    "uz": {
      "badge": "IT Park Rezidenti · Toshkent, O'zbekiston",
      "title": "Biznesingizni",
      "titleAccent": "o'zgartiruvchi texnologiyalar",
      "subtitle": "IVN Labs — aqlli yechimlar yaratuvchi dasturchilar jamoasi: AI-agentlardan tortib korporativ platformalargacha.",
      "ctaPrimary": "Loyiha boshlash",
      "ctaSecondary": "Kayslarni ko'rish",
      "stat1Value": "5+",
      "stat1Label": "yil tajriba",
      "stat2Value": "50+",
      "stat2Label": "loyiha",
      "stat3Value": "20+",
      "stat3Label": "mijoz"
    },
    "en": {
      "badge": "IT Park Resident · Tashkent, Uzbekistan",
      "title": "Technology that",
      "titleAccent": "transforms business",
      "subtitle": "IVN Labs is a team of developers building smart solutions — from AI agents to enterprise platforms. We turn ideas into products.",
      "ctaPrimary": "Start a Project",
      "ctaSecondary": "View Cases",
      "stat1Value": "5+",
      "stat1Label": "years of experience",
      "stat2Value": "50+",
      "stat2Label": "projects",
      "stat3Value": "20+",
      "stat3Label": "clients"
    }
  },
  "about": {
    "ru": {
      "label": "Кто мы",
      "title": "О нас",
      "desc1": "IVN Labs — это команда профессионалов, которая превращает идеи в инновационные технологические решения. Мы специализируемся на разработке программного обеспечения, веб-приложений, мобильных приложений и консалтинге в области IT.",
      "desc2": "Наш подход — глубокое погружение в бизнес клиента, чтобы создавать решения, которые действительно работают. Мы не просто пишем код — мы строим технологическую основу для роста вашего бизнеса.",
      "val1": "Инновации",
      "val2": "Надёжность",
      "val3": "Прозрачность",
      "val4": "Результат",
      "stat1Val": "5+",
      "stat1Label": "лет на рынке",
      "stat2Val": "20+",
      "stat2Label": "клиентов доверяют нам",
      "stat3Val": "50+",
      "stat3Label": "успешных проектов",
      "stat4Val": "100%",
      "stat4Label": "официальный резидент IT Park"
    },
    "uz": {
      "label": "Biz haqimizda",
      "title": "Biz kimiz",
      "desc1": "IVN Labs — bu g'oyalarni innovatsion texnologik yechimlarga aylantiruvchi mutaxassislar jamoasi. Biz dasturiy ta'minot, veb-ilovalar, mobil ilovalar ishlab chiqish va IT sohasida konsalting bo'yicha ixtisoslashamiz.",
      "desc2": "Bizning yondashuvimiz — mijoz biznesiga chuqur sho'ng'ish va haqiqatan ham ishlaydigan yechimlar yaratish. Biz shunchaki kod yozmaymiz — sizning biznesingiz o'sishi uchun texnologik zamin quramiz.",
      "val1": "Innovatsiya",
      "val2": "Ishonchlilik",
      "val3": "Shaffoflik",
      "val4": "Natija",
      "stat1Val": "5+",
      "stat1Label": "yil bozorda",
      "stat2Val": "20+",
      "stat2Label": "mijozlar biznga ishonadi",
      "stat3Val": "50+",
      "stat3Label": "muvaffaqiyatli loyihalar",
      "stat4Val": "100%",
      "stat4Label": "rasmiy IT Park rezidenti"
    },
    "en": {
      "label": "Who we are",
      "title": "About Us",
      "desc1": "IVN Labs is a team of professionals that turns ideas into innovative technological solutions. We specialize in software development, web applications, mobile apps, and IT consulting.",
      "desc2": "Our approach is to deeply understand the client's business in order to build solutions that truly work. We don't just write code — we build the technological foundation for your business growth.",
      "val1": "Innovation",
      "val2": "Reliability",
      "val3": "Transparency",
      "val4": "Results",
      "stat1Val": "5+",
      "stat1Label": "years in the market",
      "stat2Val": "20+",
      "stat2Label": "clients trust us",
      "stat3Val": "50+",
      "stat3Label": "successful projects",
      "stat4Val": "100%",
      "stat4Label": "official IT Park resident"
    }
  },
  "services": {
    "ru": {
      "title": "Наши услуги",
      "subtitle": "Полный цикл разработки — от идеи до продакшна",
      "ctaTitle": "Готовы начать проект?",
      "ctaDesc": "Расскажите о задаче — ответим в течение 24 часов",
      "ctaBtn": "Связаться с нами",
      "items.integration.title": "Интеграция 1С",
      "items.integration.desc": "Связываем 1С с внешними системами, автоматизируем ERP-процессы.",
      "items.web.title": "Веб-разработка",
      "items.web.desc": "Корпоративные порталы, лендинги и SaaS-платформы с современным UI/UX.",
      "items.crm.title": "CRM-системы",
      "items.crm.desc": "Разрабатываем CRM под бизнес-процессы — от простых до сложных воронок.",
      "items.bots.title": "Telegram-боты",
      "items.bots.desc": "Боты для автоматизации, AI-ассистенты, интеграции с API.",
      "items.automation.title": "Автоматизация",
      "items.automation.desc": "Цифровизация бизнес-процессов, снижение ручного труда.",
      "items.bi.title": "BI Аналитика",
      "items.bi.desc": "Power BI дашборды и аналитические отчёты для принятия решений.",
      "items.ai.title": "AI-агенты",
      "items.ai.desc": "Умные ассистенты и агенты на базе LLM для вашего бизнеса.",
      "items.bitrix.title": "Bitrix24",
      "items.bitrix.desc": "Внедрение, настройка и интеграция Bitrix24 для команд."
    },
    "uz": {
      "title": "Xizmatlarimiz",
      "subtitle": "G'oyadan produksiyagacha to'liq tsikl",
      "ctaTitle": "Loyiha boshlashga tayyormisiz?",
      "ctaDesc": "Vazifangiz haqida ayting — 24 soat ichida javob beramiz",
      "ctaBtn": "Biz bilan bog'laning",
      "items.integration.title": "1C Integratsiya",
      "items.integration.desc": "1C ni tashqi tizimlar bilan ulash, ma'lumot almashishni avtomatlashtirish.",
      "items.web.title": "Veb-dasturlash",
      "items.web.desc": "Korporativ portallar, landing sahifalar va SaaS platformalar.",
      "items.crm.title": "CRM Tizimlar",
      "items.crm.desc": "Biznes jarayonlarga moslashtirilgan CRM tizimlar.",
      "items.bots.title": "Telegram-botlar",
      "items.bots.desc": "Avtomatlashtirish uchun botlar, AI-yordamchilar.",
      "items.automation.title": "Avtomatlashtirish",
      "items.automation.desc": "Biznes jarayonlarini raqamlashtirish.",
      "items.bi.title": "BI Analitika",
      "items.bi.desc": "Power BI dashboard va analitik hisobotlar.",
      "items.ai.title": "AI-agentlar",
      "items.ai.desc": "LLM asosidagi aqlli yordamchilar.",
      "items.bitrix.title": "Bitrix24",
      "items.bitrix.desc": "Bitrix24 ni joriy etish va sozlash."
    },
    "en": {
      "title": "Our Services",
      "subtitle": "Full-cycle development — from idea to production",
      "ctaTitle": "Ready to start a project?",
      "ctaDesc": "Tell us about your task — we'll reply within 24 hours",
      "ctaBtn": "Contact us",
      "items.integration.title": "1C Integration",
      "items.integration.desc": "Connect 1C with external systems, automate data exchange and ERP processes.",
      "items.web.title": "Web Development",
      "items.web.desc": "Corporate portals, landing pages and SaaS platforms with modern UI/UX.",
      "items.crm.title": "CRM Systems",
      "items.crm.desc": "Custom CRM tailored to your business processes.",
      "items.bots.title": "Telegram Bots",
      "items.bots.desc": "Automation bots, AI assistants, API integrations.",
      "items.automation.title": "Automation",
      "items.automation.desc": "Digitize business processes, reduce manual work.",
      "items.bi.title": "BI Analytics",
      "items.bi.desc": "Power BI dashboards and analytical reports for decision-making.",
      "items.ai.title": "AI Agents",
      "items.ai.desc": "Smart assistants and LLM-based agents for your business.",
      "items.bitrix.title": "Bitrix24",
      "items.bitrix.desc": "Bitrix24 implementation, configuration and integration."
    }
  },
  "process": {
    "ru": {
      "label": "Наш процесс",
      "title": "Как мы работаем",
      "subtitle": "Прозрачный процесс от идеи до результата",
      "steps.discovery.title": "Discovery",
      "steps.discovery.desc": "Изучаем бизнес, аудиторию и задачи. Формируем техническое задание.",
      "steps.design.title": "Дизайн",
      "steps.design.desc": "Создаём UX/UI, прототипы и дизайн-систему.",
      "steps.dev.title": "Разработка",
      "steps.dev.desc": "Пишем код по agile: спринты, ревью, тесты.",
      "steps.launch.title": "Запуск",
      "steps.launch.desc": "Деплой, мониторинг и поддержка после релиза."
    },
    "uz": {
      "label": "Bizning jarayon",
      "title": "Biz qanday ishlaymiz",
      "subtitle": "G'oyadan natijagacha shaffof jarayon",
      "steps.discovery.title": "Discovery",
      "steps.discovery.desc": "Biznes, auditoriya va vazifalarni o'rganamiz.",
      "steps.design.title": "Dizayn",
      "steps.design.desc": "UX/UI, prototiplar va dizayn tizimini yaratamiz.",
      "steps.dev.title": "Dasturlash",
      "steps.dev.desc": "Agile bo'yicha kod yozamiz: sprintlar, review, testlar.",
      "steps.launch.title": "Ishga tushirish",
      "steps.launch.desc": "Deploy, monitoring va relizdan keyingi qo'llab-quvvatlash."
    },
    "en": {
      "label": "Our Process",
      "title": "How We Work",
      "subtitle": "Transparent process from idea to result",
      "steps.discovery.title": "Discovery",
      "steps.discovery.desc": "We study the business, audience and goals. Form technical specifications.",
      "steps.design.title": "Design",
      "steps.design.desc": "Create UX/UI, prototypes and design system.",
      "steps.dev.title": "Development",
      "steps.dev.desc": "We write code agile: sprints, reviews, tests.",
      "steps.launch.title": "Launch",
      "steps.launch.desc": "Deploy, monitoring and post-release support."
    }
  },
  "contact": {
    "ru": {
      "title": "Начнём проект?",
      "subtitle": "Расскажите о задаче — ответим в течение 24 часов",
      "name": "Имя",
      "email": "Email",
      "phone": "Телефон",
      "message": "Сообщение",
      "messagePlaceholder": "Опишите вашу задачу...",
      "submit": "Отправить заявку",
      "sending": "Отправляем...",
      "success": "Заявка отправлена! Свяжемся скоро.",
      "infoEmail": "info@ivnlabs.uz",
      "infoPhone": "+998 90 000 00 00",
      "infoAddress": "Ташкент, Узбекистан, IT Park"
    },
    "uz": {
      "title": "Loyiha boshlaymizmi?",
      "subtitle": "Vazifangizni ayting — 24 soat ichida javob beramiz",
      "name": "Ism",
      "email": "Email",
      "phone": "Telefon",
      "message": "Xabar",
      "messagePlaceholder": "Vazifangizni tasvirlab bering...",
      "submit": "Ariza yuborish",
      "sending": "Yuborilmoqda...",
      "success": "Ariza yuborildi! Tez orada bog'lanamiz.",
      "infoEmail": "info@ivnlabs.uz",
      "infoPhone": "+998 90 000 00 00",
      "infoAddress": "Toshkent, O'zbekiston, IT Park"
    },
    "en": {
      "title": "Start a Project?",
      "subtitle": "Tell us about your task — we'll respond within 24 hours",
      "name": "Name",
      "email": "Email",
      "phone": "Phone",
      "message": "Message",
      "messagePlaceholder": "Describe your task...",
      "submit": "Send Request",
      "sending": "Sending...",
      "success": "Request sent! We'll be in touch soon.",
      "infoEmail": "info@ivnlabs.uz",
      "infoPhone": "+998 90 000 00 00",
      "infoAddress": "Tashkent, Uzbekistan, IT Park"
    }
  },
  "testimonials": {
    "ru": {
      "label": "Отзывы",
      "title": "Что говорят клиенты",
      "subtitle": "Реальный опыт работы с IVN Labs",
      "ctaTitle": "Работали с нами?",
      "ctaDesc": "Поделитесь опытом — ваш отзыв помогает нам расти",
      "ctaBtn": "Оставить отзыв",
      "reviews.r1.name": "Азиз Н.",
      "reviews.r1.position": "CEO, Texnomart",
      "reviews.r1.text": "IVN Labs создали для нас платформу с нуля в рекордные сроки. Команда глубоко разобралась в бизнес-процессах. Конверсия выросла в 3 раза.",
      "reviews.r2.name": "Бахром Ю.",
      "reviews.r2.position": "CTO, Kapital Bank",
      "reviews.r2.text": "Высочайший технический уровень. Реализовали микросервисную архитектуру, которую внутренняя команда не могла решить год. Теперь система держит нагрузку в десятки раз больше.",
      "reviews.r3.name": "Санжар М.",
      "reviews.r3.position": "Основатель, Media Park",
      "reviews.r3.text": "Обратились за CRM и получили намного больше: интеграции, автоматизацию, BI-дашборд. Ребята сами предложили решения, о которых мы не думали.",
      "reviews.r4.name": "Нилуфар А.",
      "reviews.r4.position": "HR Director, Ucell",
      "reviews.r4.text": "Telegram-бот автоматизировал 70% нашей работы с кандидатами. Время обработки заявки сократилось с 3 дней до 4 часов. Очень довольны результатом.",
      "reviews.r5.name": "Даврон К.",
      "reviews.r5.position": "Project Manager, Realsoft",
      "reviews.r5.text": "Работаем с IVN Labs уже 2 года. Реализовали 5 совместных проектов. Всегда чётко по срокам, прозрачная коммуникация, высокое качество кода.",
      "reviews.r6.name": "Зафар Т.",
      "reviews.r6.position": "CIO, Artel",
      "reviews.r6.text": "Интеграция 1С и SAP была нашей болью. IVN Labs решили задачу за 2 месяца — 500K+ записей синхронизируются автоматически. Нулевые потери данных.",
      "form.title": "Оставить отзыв",
      "form.desc": "Расскажите о вашем опыте работы с IVN Labs",
      "form.rating": "Оценка",
      "form.name": "Имя",
      "form.namePlaceholder": "Ваше имя",
      "form.position": "Должность",
      "form.positionPlaceholder": "Ваша должность",
      "form.company": "Компания",
      "form.companyPlaceholder": "Название компании",
      "form.social": "Социальная сеть",
      "form.socialLinkPlaceholder": "Ссылка или @username",
      "form.text": "Отзыв",
      "form.textPlaceholder": "Поделитесь своим опытом...",
      "form.submit": "Отправить отзыв",
      "form.successTitle": "Спасибо за отзыв!",
      "form.successDesc": "Мы проверим и опубликуем ваш отзыв в ближайшее время"
    },
    "uz": {
      "label": "Fikrlar",
      "title": "Mijozlar nima deydi",
      "subtitle": "IVN Labs bilan ishlashning haqiqiy tajribasi",
      "ctaTitle": "Biz bilan ishladingizmi?",
      "ctaDesc": "Tajribangizni ulashing — sizning fikringiz bizga o'sishga yordam beradi",
      "ctaBtn": "Fikr qoldirish",
      "reviews.r1.name": "Aziz N.",
      "reviews.r1.position": "CEO, Texnomart",
      "reviews.r1.text": "IVN Labs bizga platformani noldan rekord vaqtda yaratdi. Jamoa biznes jarayonlarimizni chuqur o'rgandi. Konversiya 3 barobar oshdi.",
      "reviews.r2.name": "Bahrom Y.",
      "reviews.r2.position": "CTO, Kapital Bank",
      "reviews.r2.text": "Eng yuqori texnik daraja. Ichki jamoa bir yil hal qila olmagan mikroservis arxitekturasini amalga oshirdi. Endi tizim o'nlab barobar ko'p yuklamani ko'taradi.",
      "reviews.r3.name": "Sanjar M.",
      "reviews.r3.position": "Asoschisi, Media Park",
      "reviews.r3.text": "CRM uchun murojaat qildik va ko'proq narsani oldik: integratsiyalar, avtomatlashtirish, BI-dashboard. O'zlari biz o'ylamagan yechimlarni taklif qildi.",
      "reviews.r4.name": "Nilufar A.",
      "reviews.r4.position": "HR Director, Ucell",
      "reviews.r4.text": "Telegram-bot nomzodlar bilan ishimizning 70% ni avtomatlashtiirdi. Ariza ko'rib chiqish vaqti 3 kundan 4 soatga tushdi. Natijadan juda mamnunmiz.",
      "reviews.r5.name": "Davron K.",
      "reviews.r5.position": "Project Manager, Realsoft",
      "reviews.r5.text": "IVN Labs bilan 2 yildan beri ishlaymiz. 5 ta birgalikdagi loyiha amalga oshirdik. Har doim muddatiga rioya qiladi, shaffof muloqot, yuqori kod sifati.",
      "reviews.r6.name": "Zafar T.",
      "reviews.r6.position": "CIO, Artel",
      "reviews.r6.text": "1C va SAP integratsiyasi bizning dardimiz edi. IVN Labs masalani 2 oyda hal qildi — 500K+ yozuv avtomatik sinxronlanadi. Ishga tushirilganidan beri nol ma'lumot yo'qotish.",
      "form.title": "Fikr qoldirish",
      "form.desc": "IVN Labs bilan ishlash tajribangizni bayon eting",
      "form.rating": "Baho",
      "form.name": "Ism",
      "form.namePlaceholder": "Ismingiz",
      "form.position": "Lavozim",
      "form.positionPlaceholder": "Lavozimingiz",
      "form.company": "Kompaniya",
      "form.companyPlaceholder": "Kompaniya nomi",
      "form.social": "Ijtimoiy tarmoq",
      "form.socialLinkPlaceholder": "Havola yoki @username",
      "form.text": "Fikr",
      "form.textPlaceholder": "Tajribangizni ulashing...",
      "form.submit": "Fikr yuborish",
      "form.successTitle": "Fikringiz uchun rahmat!",
      "form.successDesc": "Yaqin orada sizning fikringizni ko'rib chiqib, e'lon qilamiz"
    },
    "en": {
      "label": "Testimonials",
      "title": "What clients say",
      "subtitle": "Real experience working with IVN Labs",
      "ctaTitle": "Worked with us?",
      "ctaDesc": "Share your experience — your review helps us grow",
      "ctaBtn": "Leave a Review",
      "reviews.r1.name": "Aziz N.",
      "reviews.r1.position": "CEO, Texnomart",
      "reviews.r1.text": "IVN Labs built our platform from scratch in record time. The team deeply understood our business processes. Conversion tripled in the first 3 months.",
      "reviews.r2.name": "Bahrom Y.",
      "reviews.r2.position": "CTO, Kapital Bank",
      "reviews.r2.text": "Exceptional technical expertise. They implemented a microservice architecture that our in-house team couldn't solve in a year. The system now handles 10× more load.",
      "reviews.r3.name": "Sanjar M.",
      "reviews.r3.position": "Founder, Media Park",
      "reviews.r3.text": "We came for a CRM and got much more: integrations, automation, BI dashboard. They proactively suggested solutions we hadn't even considered.",
      "reviews.r4.name": "Nilufar A.",
      "reviews.r4.position": "HR Director, Ucell",
      "reviews.r4.text": "The Telegram bot automated 70% of our candidate workflow. Application processing time dropped from 3 days to 4 hours. Extremely pleased with the outcome.",
      "reviews.r5.name": "Davron K.",
      "reviews.r5.position": "Project Manager, Realsoft",
      "reviews.r5.text": "We've been working with IVN Labs for 2 years and completed 5 projects together. Always on time, transparent communication, and high-quality code every time.",
      "reviews.r6.name": "Zafar T.",
      "reviews.r6.position": "CIO, Artel",
      "reviews.r6.text": "Integrating 1C and SAP was our biggest pain point. IVN Labs solved it in 2 months — 500K+ records sync automatically now. Zero data loss since launch.",
      "form.title": "Leave a Review",
      "form.desc": "Share your experience working with IVN Labs",
      "form.rating": "Rating",
      "form.name": "Name",
      "form.namePlaceholder": "Your name",
      "form.position": "Position",
      "form.positionPlaceholder": "Your job title",
      "form.company": "Company",
      "form.companyPlaceholder": "Company name",
      "form.social": "Social Network",
      "form.socialLinkPlaceholder": "Link or @username",
      "form.text": "Review",
      "form.textPlaceholder": "Share your experience...",
      "form.submit": "Submit Review",
      "form.successTitle": "Thank you for your review!",
      "form.successDesc": "We'll review and publish it shortly"
    }
  },
  "clients": {
    "ru": {
      "label": "Наши клиенты",
      "title": "Нам доверяют лидеры рынка",
      "subtitle": "Компании, с которыми мы успешно работаем",
      "c1": "клиентов",
      "c2": "отраслей",
      "c3": "страны"
    },
    "uz": {
      "label": "Mijozlarimiz",
      "title": "Bozor yetakchilariga ishontiramiz",
      "subtitle": "Biz muvaffaqiyatli ishlagan kompaniyalar",
      "c1": "mijoz",
      "c2": "soha",
      "c3": "davlat"
    },
    "en": {
      "label": "Our Clients",
      "title": "Trusted by market leaders",
      "subtitle": "Companies we've successfully worked with",
      "c1": "clients",
      "c2": "industries",
      "c3": "countries"
    }
  },
  "footer": {
    "ru": {
      "tagline": "Технологии будущего — сегодня",
      "rights": "© 2024 IVN Labs. Все права защищены.",
      "itpark": "Резидент IT Park Узбекистан",
      "colServices": "Услуги",
      "colCompany": "Компания",
      "colContact": "Контакт",
      "s1": "1C Интеграция",
      "s2": "Веб-разработка",
      "s3": "CRM",
      "s4": "AI-агенты",
      "s5": "BI Аналитика",
      "c1": "О нас",
      "c2": "Продукты",
      "c3": "Проекты",
      "c4": "Контакт"
    },
    "uz": {
      "tagline": "Kelajak texnologiyalari — bugun",
      "rights": "© 2024 IVN Labs. Barcha huquqlar himoyalangan.",
      "itpark": "O'zbekiston IT Park rezidenti",
      "colServices": "Xizmatlar",
      "colCompany": "Kompaniya",
      "colContact": "Aloqa",
      "s1": "1C Integratsiya",
      "s2": "Veb-dasturlash",
      "s3": "CRM",
      "s4": "AI-agentlar",
      "s5": "BI Analitika",
      "c1": "Biz haqimizda",
      "c2": "Mahsulotlar",
      "c3": "Loyihalar",
      "c4": "Aloqa"
    },
    "en": {
      "tagline": "Future technologies — today",
      "rights": "© 2024 IVN Labs. All rights reserved.",
      "itpark": "IT Park Uzbekistan Resident",
      "colServices": "Services",
      "colCompany": "Company",
      "colContact": "Contact",
      "s1": "1C Integration",
      "s2": "Web Development",
      "s3": "CRM",
      "s4": "AI Agents",
      "s5": "BI Analytics",
      "c1": "About",
      "c2": "Products",
      "c3": "Projects",
      "c4": "Contact"
    }
  },
  "nav": {
    "ru": {
      "about": "О нас",
      "team": "Команда",
      "services": "Услуги",
      "products": "Продукты",
      "projects": "Проекты",
      "process": "Процесс",
      "contact": "Контакт",
      "blog": "Блог"
    },
    "uz": {
      "about": "Biz haqimizda",
      "team": "Jamoa",
      "services": "Xizmatlar",
      "products": "Mahsulotlar",
      "projects": "Loyihalar",
      "process": "Jarayon",
      "contact": "Aloqa",
      "blog": "Blog"
    },
    "en": {
      "about": "About",
      "team": "Team",
      "services": "Services",
      "products": "Products",
      "projects": "Projects",
      "process": "Process",
      "contact": "Contact",
      "blog": "Blog"
    }
  }
};
